[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[server]
enableCORS = false
headless = true
enableXsrfProtection=false

[browser]
gatherUsageStats = false

[theme]
backgroundColor = "#2B2B2B"
textColor = "#FFFFFF"
primaryColor="#FFFFFF"